server:
  port: ${PORT:8084}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smarthome}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

clients:
  sensor-manager-url: ${SENSOR_MANAGER_URL:http://localhost:8082}
  device-handle-url: ${DEVICE_HANDLE_URL:http://localhost:8083}
